{% set name = "pyte" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9bfd1b781759e7572a6e553c010cc93eef58a19d8d1590446d84c19b1b097b0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    # according to setup.py this is needed to build
    - pytest-runner
  run:
    - python >={{ python_min }}
    # requirements from setup.py
    - wcwidth

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyte

about:
  home: http://github.com/selectel/pyte
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Simple VTXXX-compatible linux terminal emulator
  description: |
    pyte is an in memory VTXXX-compatible terminal emulator. XXX stands for a
    series of video terminals, developed by DEC between 1970 and 1995. The
    first, and probably the most famous one, was VT100 terminal, which is now a
    de-facto standard for all virtual terminal emulators. pyte follows the
    suit.
  doc_url: http://pyte.readthedocs.org/
  dev_url: https://github.com/selectel/pyte

extra:
  recipe-maintainers:
    - saraedum
